name: Publish

on:
  # push:
  #   tags:
  #     - "v*"
  push:
    branches: [feat/**]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Build Package
        shell: bash
        run: |
          npm run output:cleanup
          npm run output:setup
          npm run build:release:package

      - name: Publish Package To NPM
        run: |
          npm run deploy:staged:npm:release
